### ISSUE TITLE
Implement Workspace Dashboard

### ISSUE THREAD

**Issue by ivlevdenis** [evrone/toggl-python#11]
https://github.com/toggl/toggl_api_docs/blob/master/chapters/dashboard.md

**Comment by nifadyev** [comment]
According to [migration guide](https://engineering.toggl.com/docs/additional/v8_migration_guide/index.html) `Dashboard` is now a part of `Workspace` resource

| Verb | V8 | V9 | Additional Notes |
|--------|--------|--------|--------|
| GET | /dashboard/{workspace_id}	 | /workspaces/{workspace_id}/dashboard/all_activity	 | Also available more specific /most_active and /top_activity |

Unable to get relevant response because `Dashboard` is not available on Free plan

**Comment by nifadyev** [comment]
Closed because `Dashboard` is available only on paid plan
